from node:16

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# install dependencies
RUN npm install

# copy other project files
COPY . .

# Expose port 3000

EXPOSE 3000

# start the app

CMD ["npm", "start"]




